### ISSUE TITLE
Add ability to handle 'all files in a folder', and/or a list like *.flac, and add option to place analysis in a subdirectory.

### ISSUE THREAD

**Issue by HansJA** [joakimfors/PyMasVis#2]
This COULD be done in an external shell script, but repeatedly calling the python interpreter seems too expensive for analysing several thousand files.

Which I'd like to do with all the files on my UPnP server. For later inclusion in an image tag, so I can look at the analysis for a song while listening to it.

In order to avoid clutter, when doing mass analysis, it would be nice to have an option to place any analysis file in a subdir of the directory where the audio file was found.

So that given the command "python analyze.py -S MasVis /media/Music/*", and then
having a set of audio files in /media/Music/Beethoven, analysis files for this set of audio files will be placed in /media/Music/Beethoven/MasVis.
If nonexistent, MasVis/ must be created as needed.

**Comment by joakimfors** [comment]
It's already possible to use "globbing". That is, analyse all files in a folder "python analyze foo/bar/*.flac" or even deeper pattern matching like "python analyze.py ~/Music/*/*.flac".

I'll take a look at adding options to place the resulting image in a subdir relative to the analysed file

**Comment by HansJA** [comment]
Unless analyze.py manages the globbing on its own, deep globbing is problematic; the max command line length quickly gets in the way for anything like a reasonable UPnP server source tree.

I think a "perfect" way to deal with analyzing an entire tree would be to have a "recursive" option (-R) and accept the top of the tree as a single argument.

If there could also be a way to say "only analyse audio that is newer than an existing analysis, or hasn't been analysed yet"..... then I wouldn't have to learn gmake again.

**Comment by joakimfors** [comment]
PyMasVis uses the glob module to do its own expansion. I'll look into a "no overwrite" feature.

**Comment by HansJA** [comment]
What environments are you using this in, yourself??
Windows is the only OS I know of where the "shell" doesn't glob by default. 

So if I quote the wildcard expression, analyze.py would do the globbing???

**Comment by HansJA** [comment]
What would a "no overwrite" do???

**Comment by joakimfors** [comment]
I'm using it on OS X and Linux.

Let me restate: PyMasVis does its own glob/expansion of arguments, too. However, this requires that the argument is quoted on the command line to prevent the shell from doing the expansion:

https://github.com/joakimfors/PyMasVis/blob/master/src/analyze.py#L1017

The no overwrite option would prevent analysing/overwriting existing results.

**Comment by HansJA** [comment]
Could that be changed into "only update analysis file if audio file is newer than existing"?

**Comment by joakimfors** [comment]
Yes, I plan on providing different choices i.e. always update, never update and update if newer.

**Comment by HansJA** [comment]
Some way to say Recursively ?

**Comment by HansJA** [comment]
This is more compact:

analyze --recurse /top/dir --resultdir '.masvis' --newer \
 '*.{flac,aac,wav}

to analyze all flac, wav and aac files, that are newer than existing analyses, in the tree under /top/dir, putting and looking for analysis files in the subdir .masvis in each direction with matching files.

I suppose always creating the analyses subdir as needed i s the reasonable thing.

I assume Python can use csh style {} alternative lists for globbing?

**Comment by joakimfors** [comment]
Recursion of directory inputs, result destination directories and jpeg output format are now supported.

https://github.com/joakimfors/PyMasVis/blob/master/doc/manual.md

**Comment by HansJA** [comment]
Då ska jag testa. Du är rätt snabb, faktiskt.

Hans J. Albertsson
From my Nexus 5
Den 15 apr. 2016 13:10 skrev "Joakim Fors" <notifications@github.com>:
