### ISSUE TITLE
Python3 errors with PyMasVis (compatibility issues with Python 3)

### ISSUE THREAD

**Issue by GeekBear80** [joakimfors/PyMasVis#4]
Hello! PyMasVis is a great piece of software. However, I'd like to raise attention to an issue here... while PyMasVis works flawlessly in Python2, with Python3, (Python 3.8.5.20200721) I get this error message:

analyze.py:975: SyntaxWarning: "is" with a literal. Did you mean "=="?
if method is 'log10':
analyze.py:979: SyntaxWarning: "is" with a literal. Did you mean "=="?
if which is 'both':
analyze.py:987: SyntaxWarning: "is" with a literal. Did you mean "=="?
if method is 'linear':
analyze.py:990: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif method is 'log10':
analyze.py:999: SyntaxWarning: "is" with a literal. Did you mean "=="?
if which is 'max':
analyze.py:1001: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif which is 'min':
analyze.py:1003: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif which is 'both':
Traceback (most recent call last):
File "analyze.py", line 45, in <module>
  from matplotlib.pyplot import (
ImportError: cannot import name 'hold' from 'matplotlib.pyplot' (C:\Python38\lib\site-packages\matplotlib\pyplot.py)

And then no analysis after this error message. Might be worth upgrading PyMasVis to conform with Python3, because Python2 is no longer receiving updates since January 2020, and pip for Python2 will also cease support soon, which I guess means that it will be difficult to install the required components and libraries for new users or after having done a fresh install, such as FFmpeg, NumPy, SciPy and so on. Other than that, keep up the good work and I hope you keep updating and improving PyMasVis! This is a very important tool for us audiophiles.

**Comment by RosensRauk** [comment]
How about a docker image- and or kodi- add-on?
//Fritz

**Comment by joakimfors** [comment]
Finally got around to pulling the whole project into this decade. Still a lot of cleanup left but it's getting there. Hopefully I'll get around to making a docker image and some CI/CD soonish.
